apiVersion: v1
kind: Service
metadata:
  name: mysql-0-service
  namespace: mysql-cluster
  labels:
    app: mysql-0-service
spec:
  type: NodePort
  selector:
    app: mysql-0
  ports:
  - protocol: TCP
    port: 3306 # 服务端口, 内部可访问
    targetPort: 3306 #Pod端口
    nodePort: 33060 #node开放的端口,外部访问

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-1-service
  namespace: mysql-cluster
  labels:
    app: mysql-1-service
spec:
  type: NodePort
  selector:
    app: mysql-1
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 33070

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-2-service
  namespace: mysql-cluster
  labels:
    app: mysql-2-service
spec:
  type: NodePort
  selector:
    app: mysql-2
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 33070