apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-0
  namespace: mysql-cluster
  labels:
    app: mysql-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-0
  template:
    metadata:
      labels:
        app: mysql-0
    spec:
      containers:
        - name: mysql-0
          image: mysql:5.7
          args: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_general_ci","--server-id=100","--log-bin=mysql-bin"]
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql/mysql-0" #文件路径,以挂载的pvc为基准
              name: mysql-data
            - mountPath: "/var/log/mysql"
              subPath: "mysql/mysql-0-log" #文件路径,以挂载的pvc为基准
              name: mysql-data
            - mountPath: "/etc/mysql/my.cnf"
              subPath: "mysql.cnf"
              name: mysql-cnf
          env:
            - name: MYSQL_ROOT_PASSWORD #设置MySQL的root密码
              value: "123456"
            - name: TZ
              value: Asia/Shanghai

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: gluster-claim-mysql
        - name: mysql-cnf
          configMap:
            name: mysql
            items:
            - key: mysql.cnf       #key为文件名称
              path: mysql.cnf      #文件路径内容

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-1
  namespace: mysql-cluster
  labels:
    app: mysql-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-1
  template:
    metadata:
      labels:
        app: mysql-1
    spec:
      containers:
        - name: mysql-1
          image: mysql:5.7
          args: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_general_ci","--server-id=300","--log-bin=mysql-bin","--read-only=1"]
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql/mysql-1" #文件路径,以挂载的pvc为基准
              name: mysql-data
            - mountPath: "/var/log/mysql"
              subPath: "mysql/mysql-1-log" #文件路径,以挂载的pvc为基准
              name: mysql-data
            - mountPath: "/etc/mysql/my.cnf"
              subPath: "mysql.cnf"
              name: mysql-cnf
          env:
            - name: MYSQL_ROOT_PASSWORD #设置MySQL的root密码
              value: "123456"
            - name: TZ
              value: Asia/Shanghai

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: gluster-claim-mysql
        - name: mysql-cnf
          configMap:
            name: mysql
            items:
            - key: mysql.cnf       #key为文件名称
              path: mysql.cnf      #文件路径内容
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-2
  namespace: mysql-cluster
  labels:
    app: mysql-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-2
  template:
    metadata:
      labels:
        app: mysql-2
    spec:
      containers:
        - name: mysql-2
          image: mysql:5.7
          args: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_general_ci","--server-id=300","--log-bin=mysql-bin","--read-only=1"]
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql/mysql-2" #文件路径,以挂载的pvc为基准
              name: mysql-data
            - mountPath: "/var/log/mysql"
              subPath: "mysql/mysql-2-log" #文件路径,以挂载的pvc为基准
              name: mysql-data
            - mountPath: "/etc/mysql/my.cnf"
              subPath: "mysql.cnf"
              name: mysql-cnf
          env:
            - name: MYSQL_ROOT_PASSWORD #设置MySQL的root密码
              value: "123456"
            - name: TZ
              value: Asia/Shanghai

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: gluster-claim-mysql
        - name: mysql-cnf
          configMap:
            name: mysql
            items:
            - key: mysql.cnf       #key为文件名称
              path: mysql.cnf      #文件路径内容