apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  namespace: mark-k8s-dev
  labels:
    app: mqtt-service
spec:
  type: NodePort
  selector:
    app: mqtt
  ports:
  - name: port1
    protocol: TCP
    port: 8883 #服务端口, 内部可访问
    targetPort: 8883 #Pod端口
  - name: port2
    protocol: TCP
    port: 1883 #服务端口, 内部可访问
    targetPort: 1883 #Pod端口 
