apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-1
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
        - name: zookeeper-1
          image: docker-harbor.clubs999.com/public/zookeeper
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: "/data"
              subPath: "zookeeper/zookeeper-1" #文件路径,以挂载的pvc为基准
              name: zookeeper-data
            - mountPath: "/datalog"
              subPath: "zookeeper/zookeeper-1-log" #文件路径,以挂载的pvc为基准
              name: zookeeper-data

          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: "server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper-2-service:2888:3888;2181 server.3=zookeeper-3-service:2888:3888;2181"

      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-2
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-2
  template:
    metadata:
      labels:
        app: zookeeper-2
    spec:
      containers:
        - name: zookeeper-2
          image: docker-harbor.clubs999.com/public/zookeeper
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: "/data"
              subPath: "zookeeper/zookeeper-2" #文件路径,以挂载的pvc为基准
              name: zookeeper-data
            - mountPath: "/datalog"
              subPath: "zookeeper/zookeeper-2-log" #文件路径,以挂载的pvc为基准
              name: zookeeper-data

          env:
            - name: ZOO_MY_ID
              value: "2"
            - name: ZOO_SERVERS
              value: "server.1=zookeeper-1-service:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper-3-service:2888:3888;2181"

      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-3
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-3
  template:
    metadata:
      labels:
        app: zookeeper-3
    spec:
      containers:
        - name: zookeeper-3
          image: docker-harbor.clubs999.com/public/zookeeper
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: "/data"
              subPath: "zookeeper/zookeeper-3" #文件路径,以挂载的pvc为基准
              name: zookeeper-data
            - mountPath: "/datalog"
              subPath: "zookeeper/zookeeper-3-log" #文件路径,以挂载的pvc为基准
              name: zookeeper-data

          env:
            - name: ZOO_MY_ID
              value: "3"
            - name: ZOO_SERVERS
              value: "server.1=zookeeper-1-service:2888:3888;2181 server.2=zookeeper-2-service:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181"

      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub