apiVersion: v1
kind: Service
metadata:
  name: zookeeper2181-service
  namespace: mark-k8s-dev
  labels:
    app: zookeeper2181-service
spec:
  type: NodePort
  selector:
    app: zookeeper2181
  ports:
  - name: port1
    protocol: TCP
    port: 2181 # 服务端口, 内部可访问
    targetPort: 2181 #Pod端口
    

    