apiVersion: v1
kind: Service
metadata:
  name: srs-service
  namespace: mark-k8s-dev
  labels:
    app: srs-service
spec:
  type: NodePort
  selector:
    app: srs
  ports:
  - name: port1
    protocol: TCP
    port: 1935 # 服务端口, 内部可访问
    targetPort: 1935 #Pod端口
    
  - name: port2
    protocol: TCP
    port: 1985 # 服务端口, 内部可访问
    targetPort: 1985 #Pod端口

  - name: port3
    protocol: TCP
    port: 8080 # 服务端口, 内部可访问
    targetPort: 8080 #Pod端口

