apiVersion: v1
kind: Service
metadata:
  name: jartest-service
  namespace: mark-k8s-dev
  labels:
    app: jartest-service
spec:
  type: NodePort
  selector:
    app: jartest
  ports:
  - name: port1
    protocol: TCP
    port: 8880 #服务端口, 内部可访问
    targetPort: 8880 #Pod端口
