apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
      release: canary
  template:
    metadata:
      labels:
        app: tomcat
        release: canary
    spec:
      containers:
       - name: tomcat
         image: tomcat:8.5.32-jre8-alpine
         ports:
            - name: http
              containerPort: 8080
         volumeMounts:
            - mountPath: "/usr/local/tomcat/webapps"
              subPath: "tomcat-projects/tomcat-webapps" #文件路径,以挂载的pvc为基准
              name: tomcat-data
      volumes:
        - name: tomcat-data
          persistentVolumeClaim:
            claimName: gluster-claim-default-pub

apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: default
  labels:
    app: tomcat-service
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
  - name: port1
    protocol: TCP
    port: 8080 #服务端口, 内部可访问
    targetPort: 8080 #Pod端口
