apiVersion: v1
kind: Service
metadata:
  name: nginx-tcp-service
  namespace: mark-k8s-dev
  labels:
    app: nginx-tcp-service
spec:
  type: NodePort
  selector:
    app: nginx-tcp
  ports:
  - name: port1
    protocol: TCP
    port: 1521 # 服务端口, 内部可访问
    targetPort: 1521 #Pod端口
    
