apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
  namespace: mark-k8s-dev
  labels:
    app: ubuntu-service
spec:
  type: NodePort
  clusterIP: 10.96.11.101 #service ip,自定义
  selector:
    app: ubuntu
  ports:
  - name: port1
    protocol: TCP
    port: 22 #服务端口, 内部可访问
    targetPort: 22 #Pod端口

