apiVersion: v1
kind: Service
metadata:
  name: testhtml-service
  namespace: mark-k8s-dev
  labels:
    app: testhtml-service
spec:
  type: NodePort
  selector:
    app: testhtml
  ports:
  - name: port1
    protocol: TCP
    port: 80 # 服务端口, 内部可访问
    targetPort: 80 #Pod端口
    
