apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
  labels:
    app: gitlab-service
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
  - name: port1
    protocol: TCP
    port: 8929 # 服务端口, 内部可访问
    targetPort: 8929 #Pod端口
    
  - name: port2
    protocol: TCP
    port: 22 # 服务端口, 内部可访问
    targetPort: 22 #Pod端口
    