apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mark-k8s-dev
  labels:
    app: mongodb-service
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - name: port1
    protocol: TCP
    port: 27017 # 服务端口, 内部可访问
    targetPort: 27017 #Pod端口
    
