apiVersion: v1
kind: Service
metadata:
  name: tinode-chat-service
  namespace: tinode-chat
  labels:
    app: tinode-chat-service
spec:
  type: NodePort
  selector:
    app: tinode-chat
  ports:
  - name: port1
    protocol: TCP
    port: 6060 # 服务端口, 内部可访问
    targetPort: 6060 #Pod端口
  - name: port2
    protocol: TCP
    port: 6222 # 服务端口, 内部可访问
    targetPort: 6222 #Pod端口 
