apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  labels:
    app: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: port1
    protocol: TCP
    port: 8080 # 服务端口, 内部可访问
    targetPort: 8080 #Pod端口
    
  - name: port2
    protocol: TCP
    port: 50000 # 服务端口, 内部可访问
    targetPort: 50000 #Pod端口
    