apiVersion: v1
kind: Service
metadata:
  name: vpn-l2tp-service
  namespace: default
  labels:
    app: vpn-l2tp-service
spec:
  type: NodePort
  selector:
    app: vpn-l2tp
  ports:
  - name: port1
    protocol: UDP
    port: 500 # 服务端口, 内部可访问
    targetPort: 500 #Pod端口
    
  - name: port2
    protocol: UDP
    port: 4500 # 服务端口, 内部可访问
    targetPort: 4500 #Pod端口
    