version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: docker-harbor.clubs999.com/public/kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - /home/opts/openvpn/data/:/etc/openvpn
         
    dns:
      - "10.96.0.10"
