apiVersion: v1
kind: Service
metadata:
  name: minio9000-service
  namespace: minio
  labels:
    app: minio9000-service
spec:
  type: NodePort
  selector:
    app: minio9000
  ports:
  - protocol: TCP
    port: 9000 # 服务端口, 内部可访问
    targetPort: 9000 #Pod端口
