apiVersion: v1
kind: Service
metadata:
  name: centos7-service
  namespace: mark-k8s-dev
  labels:
    app: centos7-service
spec:
  type: NodePort
  clusterIP: 10.96.10.101 #service ip,自定义
  selector:
    app: centos7
  ports:
  - name: port1
    protocol: TCP
    port: 22 #服务端口, 内部可访问
    targetPort: 22 #Pod端口

