apiVersion: v1
kind: Service
metadata:
  name: zookeeper-kafka-service
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-kafka-service
spec:
  type: NodePort
  selector:
    app: zookeeper-kafka
  ports:
  - protocol: TCP
    port: 2181 # 服务端口, 内部可访问
    targetPort: 2181 #Pod端口

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-service
  namespace: mark-k8s-dev
  labels:
    app: kafka-1-service
spec:
  type: NodePort
  selector:
    app: kafka-1
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-service
  namespace: mark-k8s-dev
  labels:
    app: kafka-2-service
spec:
  type: NodePort
  selector:
    app: kafka-2
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3-service
  namespace: mark-k8s-dev
  labels:
    app: kafka-3-service
spec:
  type: NodePort
  selector:
    app: kafka-3
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
