apiVersion: v1
kind: Service
metadata:
  name: wowza-service
  namespace: mark-k8s-dev
  labels:
    app: wowza-service
spec:
  type: NodePort
  selector:
    app: wowza
  ports:
  - name: port1
    protocol: TCP
    port: 1935 # 服务端口, 内部可访问
    targetPort: 1935 #Pod端口
    
  - name: port2
    protocol: TCP
    port: 8086 # 服务端口, 内部可访问
    targetPort: 8086 #Pod端口

  - name: port3
    protocol: TCP
    port: 8087 # 服务端口, 内部可访问
    targetPort: 8087 #Pod端口

  - name: port4
    protocol: TCP
    port: 8088 # 服务端口, 内部可访问
    targetPort: 8088 #Pod端口
    