apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: tinode-chat
  labels:
    app: influxdb-service
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
  - name: port1
    protocol: TCP
    port: 8086 # 服务端口, 内部可访问
    targetPort: 8086 #Pod端口
  - name: port2
    protocol: TCP
    port: 8088 # 服务端口, 内部可访问
    targetPort: 8088 #Pod端口   
